print("hola mundo")
print("este es otro cambio")
print("me encanta estudiar Python")
print("Estudiar con Python Total es super divertido")
print(500+55)
print("esta linea no quiero que se ejecute")
print ("linea 1\n" "linea 2\n" "linea 3\n")
print("A\t" "B\t" "c\t")
print("D\t" "E\t" "F\t")
print("G\t" "H\t" "I\t")